### ISSUE TITLE
Mixed content on demo page

### ISSUE THREAD

**Issue by jaydiablo** [szynszyliszys/repaintless#2]
I use the SSL Everywhere extension, so when I visit the demo page, I'm changed to hit the https:// version of the demo:  https://szynszyliszys.github.io/repaintless/

Unfortunately, that page loads jquery from http://code.jquery.com/jquery-1.12.0.min.js which is blocked by my browser since it's not https://

Jquery's CDn supports https, so would be nice if you could change that script load to https://code.jquery.com/jquery-1.12.0.min.js instead, thanks!  (I looked to make a PR, but I don't think the demo page's source lives in this repo).

**Comment by jaydiablo** [comment]
Spoke too soon, found the gh-pages branch, PR submitted. :)

**Comment by szynszyliszys** [comment]
@jaydiablo thanks fo spotting this!
