### ISSUE TITLE
Integration with frameworks and expand library

### ISSUE THREAD

**Issue by AllanPinheiroDeLima** [szynszyliszys/repaintless#7]
Hi, I was womdering if you are looking for contribution to this library. 

I would like to make an integration with vue and develop new animations to the stack :)

**Comment by szynszyliszys** [comment]
Hi Allan, 
About the integration: great, it would be nice to see that (although I never used Vue so would be great to find someone versed to do a code review).

About the new animations: what kind of animations do you have in mind?

By the way: I am the creator of this library and believe I am the only maintainer here and I am not a guy, so it would be nice to use more inclusive language in such situations (such us: "I was wondering if your team/you"). Thank you in advance :)

**Comment by AllanPinheiroDeLima** [comment]
> By the way: I am the creator of this library and believe I am the only maintainer here and I am not a guy, so it would be nice to use more inclusive language in such situations (such us: "I was wondering if your team/you"). Thank you in advance :)

I'm sorry I didn't pay attention :( 
I've updated the comment. I'm really sorry

About the integration, it would be a nice change of pace and by making the library compatible with major frameworks like Angular, React and Vue could expand the usage of great animation techniques around the world, since your lib is paying enough attention to HOW animation should be done

About the animations, I would like to increment the lib increasing the amount of available animations based on libs like Animate.css, Magic.css and many others. Also my team and I are developing an application and we would use the use cases we see here to incrementally update it with our costumers data usage.

About my past comment, I'm really sorry and I promise I'll pay more attention

**Comment by szynszyliszys** [comment]
Hi @AllanPinheiroDeLima I am sorry I didn't reply earlier, I missed the notification somehow. I unfortunatelly have no time currently to work on the integrations, but if you were to propose a PR I would be happy to look at it. 

With adding new animation we would have to make sure they are all repaintless (using only opacity and transforms) to keep the library promise alive.
